### ISSUE TITLE
10-bit output

### ISSUE THREAD

**Issue by YomikoR** [Endilll/vapoursynth-preview#32]
In Linux with X11 there's native support for 10-bit color. Since 10-bit RGB formats are available in Qt and are packed as 32-bit as well, is it possible to preview in 10-bit, after changing to  v4 API of VS?

**Comment by Endilll** [comment]
Short answer: yes
Long answer:
1) I don't have a display to test if it's working properly
2) Qt is likely to support 10-bit format
3) 10-bit formats are not a target Qt optimizes rendering for, which means playback will be somewhat slower
4) it's not tied to APIv4 in any way

**Comment by YomikoR** [comment]
Thanks for the quick reply.

> it's not tied to APIv4 in any way

Yep, I mentioned APIv4 because we may not *resize* to COMPATBGR32 for 10-bit output.

**Comment by YomikoR** [comment]
I made some primary attempts with numpy and managed to pack RGB30 (and RGB24, too, see https://github.com/YomikoR/vapoursynth-preview/commit/46551b2e34ddcf8387d5e8422fb23b471503d0cb). It seems 10-bit inputs are accepted but not well rendered on the screen (e.g. compared to mpv and certain image viewers) with only the frame image creation modified. I would like to call it a day.

**Comment by YomikoR** [comment]
I think I found where the conversion to 8-bit was taken. In https://github.com/Endilll/vapoursynth-preview/blob/5fad872e8fdb06a81693a97571e4d47b010dde28/vspreview/widgets/custom/graphicsview.py#L103
change it to
` self._graphics_item.setPixmap(Qt.QPixmap.fromImage(self._image, Qt.Qt.NoFormatConversion)) `

**Comment by Endilll** [comment]
Thanks for digging this up.
