### ISSUE TITLE
AUR Package

### ISSUE THREAD

**Issue by wallace11** [Endilll/vapoursynth-preview#4]
I hope you don't mind that I created an [AUR package](https://aur.archlinux.org/packages/vapoursynth-preview-git/) for this project.
I had to create a [custom script](https://aur.archlinux.org/cgit/aur.git/tree/vspreview?h=vapoursynth-preview-git) for it to be accessible system-wide.

Cheers.

**Comment by Endilll** [comment]
I have plans to publish it on PyPI, but it feels like it's a long way before I consider it worth anyone's attention. But if someone finds it useful as it is now, I'm OK with it.
Thank you for your efforts.
