### ISSUE TITLE
Remember the windows size and location, etc.

### ISSUE THREAD

**Issue by YomikoR** [Endilll/vapoursynth-preview#7]
It seems each time the program lauches the window takes the same position. I thought it was fine until I put the Windows taskbar on top and it covers the titlebar of the program...
![unknown](https://user-images.githubusercontent.com/64504948/85801876-67115800-b709-11ea-95ab-ea1d1a9465bc.png)
By resizing at the bottom right corner the titlebar will be back. But we don't wish to do it every time.

**Comment by YomikoR** [comment]
It seems Windows binaries remember window locations when exit, but PyQt programs won't automatically do so.
I made a simple patch for myself following [this link](https://stackoverflow.com/a/33923578), though I don't know how to save to local yaml.

**Comment by Endilll** [comment]
Thanks for bringing up this long-standing issue and proposing a fix.
It's now upstream, except for width, which is still resetting.

**Comment by YomikoR** [comment]
> It's now upstream, except for width, which is still resetting.

But it works perfectly as expected on my PC without the width issue. Thank you!
